language: php
sudo: false
php:
    - 5.6

matrix:
  allow_failures:
    - php: 7.0


before_install:
    - sh -c ./build/install-neo.sh
    - neo4j-enterprise-$NEO_VERSION/bin/neo4j start > null
    - composer self-update

before_script:
    - composer install --prefer-source --no-interaction

script:
    - vendor/bin/behat

notifications:
    email: "christophe@graphaware.com"